/**
 * Plain-text CLI reference for `apex help` (no config, no plugins).
 * Keep in sync with resolveCliCommand in index.ts.
 */
export function printApexCliHelp(write: (line: string) => void = console.log): void {
  write('Apex CLI')
  write('')
  write('Getting started')
  write('  apex --version | -v | version   Print installed version (from package.json)')
  write('  apex                    Open the control plane (TUI)')
  write('                          In the TUI: /help lists slash commands (e.g. /model, /agent).')
  write('  apex doctor             Config, daemon health, log paths')
  write('  apex runtime-info       Local runtime URL, token file metadata (not the secret),')
  write('                          install root, /health + authenticated probe (see --json)')
  write('  apex onboard            First-time setup')
  write('  apex help               Show this message')
  write('')
  write('Daemon & install')
  write('  apex daemon             Run the runtime daemon (foreground)')
  write('                          First successful start creates ~/.apex/runtime.token (0600).')
  write('                          HTTP /api/* (not /health) needs Authorization: Bearer <token>')
  write('                          or X-Apex-Token (see docs/OPERATOR_TRUST.txt).')
  write('  apex launchd-install    Install the launchd plist (sets APEX_INSTALL_ROOT)')
  write('  apex update             Suggested upgrade steps')
  write('  apex release-pack       Maintainer: pack a release')
  write('  apex release-verify     Maintainer: verify a release')
  write('')
  write('Pairing & gateways')
  write('  apex pairing …          Channel pairing helpers')
  write('')
  write('Runtime service (HTTP API)')
  write('  apex runtime-info [--json]')
  write('  apex service-status')
  write('  apex service-safe <on|off>')
  write('  apex service-model <source> <sourceId> <model>')
  write('  apex service-sandbox <source> <sourceId> <default|strict|off>')
  write('  apex service-approvals')
  write('  apex service-approve <id>')
  write('  apex service-deny <id>')
  write('  apex service-sessions')
  write('')
  write('Files')
  write('  apex files preview <sourceDir> <baseTargetDir> [options]')
  write('                          Plan sort into category folders; preview only (no writes).')
  write('    Options: --json  --verbose|-v  --pattern  --extensions  --max-files')
  write('  apex files apply <sourceDir> <baseTargetDir> | --from-json <file.json>')
  write('                          Execute moves. Requires --yes or --dry-run.')
  write('    Options: --on-collision error|skip|suffix  --pattern …  --extensions …  --max-files …')
  write('')
}
